DropsOfLife/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('createRequest/', include('Requester.createRequest.urls')),
    path('profile/', include('user.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Requester/createRequest/urls.py
from django.urls import path
from . import views


app_name = 'createRequest'
urlpatterns = [
    path('', views.index, name='index'),
    path('process/', views.processRequest, name='processRequest'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

user/urls.py
from django.urls import path
from . import views


app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),
]

Requester/createRequest/models.py
from django.db import models


# Each request is connected to exactly one user
# A user can have many requests
#      many            one
# User -------------------- Request
class Request(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    hospital = models.CharField(max_length=100, blank=True)
    blood_type = models.CharField(max_length=10)
    urgency = models.CharField(max_length=10)
    prescription_link = models.CharField(max_length=100)
    date = models.DateField('Required within')

    def __str__(self):
        return self.name + " --- " + self.blood_type + " --- " + self.urgency

home/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

user/models.py
from ctypes import addressof
from django.db import models
import datetime

# Create your models here.


class Disease(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=50, blank=True)
    dateOfBirth = models.DateField('Date of Birth')
    lastDateOfDonation = models.DateTimeField('Last Donation date', blank=True)
    gender = models.CharField(max_length=20)
    bloodType = models.CharField(max_length=10)
    address = models.CharField(max_length=200)
    isDonor = models.BooleanField()
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=30)
    donationCount = models.IntegerField(default=0)

    diseases = models.ManyToManyField(Disease, blank=True)

    def __str__(self):
        return self.name


# class hasDisease(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     diseases = models.ForeignKey(Diseases, on_delete=models.CASCADE)
#     fromDate = models.DateField('Diagnosis date')

Requester/createRequest/views.py
from datetime import datetime

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpResponseRedirect, FileResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

import DropsOfLife.settings
from .models import Request


def index(request):
    context = {}
    return render(request, "forms-elements.html", context)


# After filling up create request form, this function is called for retrieving the
# form information for verification and creating new entry in the database
# Each request is stored in the Request table (see models.py)
def processRequest(request):
    name = request.POST.get('name')
    blood_type = request.POST.get('blood_type')
    email = request.POST.get('email')
    phone = request.POST.get('phone')
    address = request.POST.get('address')
    hospital = request.POST.get('hospital')
    prescription = request.FILES.get('prescription')
    required_date = request.POST.get('required_date')
    required_time = request.POST.get('required_time')
    urgency = request.POST.get('gridRadios')

    response = name + ", " + blood_type + ", " + email + ", " + phone + ", " + address + ", " + hospital + ", " + urgency
    print(response)

    fs = FileSystemStorage()
    filename = fs.save(prescription.name, prescription)
    uploaded_file_url = fs.url(filename)
    response = 'File Upload Successful. Go to this link: ' + uploaded_file_url
    prescription_link = uploaded_file_url
    print(response)

    if not required_date:
        rqst = Request(
            name=name,
            phone=phone,
            address=address,
            hospital=hospital,
            blood_type=blood_type,
            urgency=urgency,
            prescription_link=prescription_link
        )
    else:
        rqst = Request(
            name=name,
            phone=phone,
            address=address,
            hospital=hospital,
            blood_type=blood_type,
            urgency=urgency,
            prescription_link=prescription_link,
            date=required_date
        )

    rqst.save()

    return render(request, "form-submitted.html", {'prescription': prescription_link})

home/views.py
from django.shortcuts import render, HttpResponse

from Requester.createRequest.models import Request


# def myrev(item):
#     revitem = []
#     for i in item:
#         revitem.append(i)
#
#     return revitem.reverse()


def index(request):
    request_immediate = Request.objects.all().filter(urgency='Immediate').order_by('-date').reverse()
    request_standby = Request.objects.all().filter(urgency='Stand By').order_by('-date').reverse()
    request_longterm = Request.objects.all().filter(urgency='Long Term').order_by('-date').reverse()

    # request_standby = myrev(request_standby)

    context = {
        'request_immediate': request_immediate,
        'request_standby': request_standby,
        'request_longterm': request_longterm
    }
    return render(request, "DropsOfLifeHomepage.html", context)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Question, Choice


def index(request):
    # return HttpResponse("Hello world! This is index of polls.")
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    return HttpResponse("You're voting on question %s" % question_id)

user/views.py
from django.shortcuts import render, get_object_or_404, redirect

import DropsOfLife.settings
from .models import User, Disease
from datetime import datetime

# Create your views here.


def index(request):
    context = {}

    user_disease = []
    valid_donors = []
    diseases = Disease.objects.all()
    for d in diseases:
        users = User.objects.filter(diseases__name=d.name)
        for u in users:
            user_disease.append({'name': u.name, 'disease': d.name})
            print(u.name + " " + d.name)

    donors = User.objects.all()
    for d in donors:
        delta = datetime.now().date() - d.dateOfBirth
        if delta.days > 40 and d.isDonor:
            valid_donors.append({'name': d.name})

    context['user_disease'] = user_disease
    context['valid_donors'] = valid_donors

    return render(request, 'user/index.html', context)

Requester/createRequest/templates/createRequest/index.html
{% extends 'skeleton/skeleton.html' %}

{% block myBody %}
    <div class="request-form">
        <form action="{% url 'createRequest:processRequest' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="banner">
                <h2>Create a Request</h2>
            </div>
            <br/>
            <fieldset>
                <legend>Request Form</legend>
                <div class="colums">
                    <div class="item">
                        <input id="fname" type="text" name="fname" placeholder="Name" required/>
                    </div>
                    <div class="item">
                        <input id="phone" type="tel" name="phone" placeholder="Contact No." required/>
                    </div>
                    <div class="item">
                        <input id="saddress" type="text" name="city" placeholder="Address" required/>
                    </div>

                    <div id="googleMap" style="margin:auto;width:40%;height:400px;"></div>

                    <div class="item">
                        <input id="hospital" type="text" name="hospital_name" placeholder="Hospital" required/>
                    </div>
                    <div class="item">
                        <input id="blood_type" type="text" name="blood_type" placeholder="Blood Type" required/>
                    </div>
                    <div class="item">
                        <input id="urgency" type="text" name="urgency" placeholder="Urgency" required/>
                    </div>
                    <div class="item">
                        <legend>Prescription:</legend>
                        <input type="file" id="prescription" name="prescription" placeholder="Prescription" required/>
                    </div>
            </fieldset>
            <div class="btn-block">
                <button type="order" href="{% url 'createRequest:processRequest' %}">Confirm Request</button>
            </div>
        </form>
    </div>
{% endblock %}


{% block myScript %}
<script>
    function myMap() {

        const myLatLng = {
            lat: 23.7461,
            lng: 90.3742
        };

        var mapProp = {
            center: myLatLng,
            zoom: 17,
        };

        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

        var marker = new google.maps.Marker({
            position: myLatLng,
            animation: google.maps.Animation.DROP
        });

        marker.setDraggable(true);
        marker.setClickable(true);
        marker.setMap(map);

        marker.addListener('position_changed', printMarkerLocation);

        function printMarkerLocation() {
            var pos = 'Lat: ' + marker.position.lat() + ' Lng:' + marker.position.lng();
            console.log(pos);
            document.getElementById("saddress").value = pos
        }
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzH5qc_mytBR1OydCEd87eKZ-_u-fP8sQ&callback=myMap"></script>
{% endblock %}

home/templates/home/index.html
{% extends 'skeleton/skeleton.html' %}

{% block myBody %}

    <div class="header">
        Welcome!! Have a nice day.
    </div>
    <div class="info">
        <div>
            New bullshit in town
        </div>

        <h2>Requests</h2>
        <ul>
            {% for r in rqst %}
            <li>Name:       {{ r.name }}</li>>
            <li>Phone:      {{ r.phone }}</li>>
            <li>Address:    {{ r.address }}</li>>
            <li>Hospital:   {{ r.hospital }}</li>>
            <li>Blood Type: {{ r.blood_type }}</li>>
            <li>Urgency:    {{ r.urgency }}</li>>
            <li>Date:       {{ r.pub_date }}</li>>
            <li>Prescription: {{ r.prescription_link }}</li>>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

home/templates/home/login.html
{% extends 'skeleton/skeleton.html' %}

{% block myBody %}
<form method="post">
    {% csrf_token %}
    <label for="fname">First name:</label><br>
    <input type="text" id="fname" name="fname" value="John"><br>
    <input type="submit" value="Submit">
</form>
{% endblock %}

home/templates/skeleton/navbar.html
<div class="topnav">
    <h1>"Donate Blood, Save Lives"</h1>
    <input type="text" placeholder="Search.." name="search">
    <button type="submit"><i class="fa fa-search"></i></button>
    <a href="#">Messages</a>
    <a href="#">Notifications</a>
</div>

home/templates/skeleton/sidebar.html
<div class="sidebar">
    <h2>Drops Of Life</h2>
    <ul>
        <li><a href="{% url 'home:index' %}"><i class="fas fa-home"></i>Home</a></li>
        <li><a href="{% url 'user:index' %}"><i class="fas fa-user"></i>Profile</a></li>
        <li><a href="#"><i class="fas fa-users"></i></i>Friend Requests</a></li>
        <li><a href="{% url 'createRequest:index' %}"><i class="fas fa-project-diagram"></i>Request Blood</a></li>
        <li><a href="#"><i class="fas fa-project-diagram"></i>My Requests</a></li>
        <li><a href="#"><i class="fas fa-project-diagram"></i>Blood Banks</a></li>
        <li><a href="#"><i class="fas fa-blog"></i>Blogs</a></li>
        <li><a href="#"><i class="fas fa-address-book"></i>Contact</a></li>
        <li><a href="#"><i class="fas fa-address-card"></i>About Us</a></li>
        <li><a href="#"><i class="fa-solid fa-right-from-bracket"></i></i> Sign out</a></li>
    </ul>
    <div class="social_media">
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
    </div>
</div>

polls/templates/polls/detail.html
Detail of {{ question.pk }}

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/form-submitted.html
{% extends 'skeleton.html' %}

{% block main %}
<p>You're Requested has been broadcasted</p>
<a href="http://127.0.0.1:8000{{ prescription }}">Prescription Uploaded Here</a>
{% endblock %}

templates/forms-elements.html
{% extends 'skeleton.html' %}
{% block main %}
<div class="pagetitle">
    <h1>Blood Request Form</h1>
    <nav></nav>
</div>
<!-- End Page Title -->
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Fill up the required fields</h5>
                    <!-- General Form Elements -->
                    <form method="post" action="{% url 'createRequest:processRequest' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label required">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" id="name" required/>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label required">Blood Type</label>
                            <div class="col-sm-10">
                                <select class="form-select" aria-label="Default select example" name="blood_type" id="blood_type" required>
                                <!--                      <option selected>Select Blood Group</option>-->
                                <option value="A+">A+</option>
                                <option value="A">A-</option>
                                <option value="B+">B+</option>
                                <option value="B-">B-</option>
                                <option value="AB+">AB+</option>
                                <option value="AB-">AB-</option>
                                <option value="O+">O+</option>
                                <option value="O-">O-</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" name="email" id="email">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label required">Contact no</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="phone" id="phone" required/>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label required">Address</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="address" name="address" required/>
                            </div>
                        </div>
                        <div class="row mb-3" id="googleMap" style="margin-left:auto;margin-right:0;width:80%;height:400px;">
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Hospital</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="hospital" id="hospital">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label required">Prescription Upload</label>
                            <div class="col-sm-10">
                                    <input type="file" id="prescription" name="prescription" placeholder="Prescription" required/>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label required">Required Within</label>
                            <div class="col-sm-10">
                                <input type="date" class="form-control" name="required_date" id="required_date" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Time</label>
                            <div class="col-sm-10">
                                <input type="time" class="form-control" name="required_time" id="required_time">
                            </div>
                        </div>
                        <fieldset class="row mb-3">
                            <legend class="col-form-label col-sm-2 pt-0 required">Request Urgency</legend>
                            <div class="col-sm-10">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="Immediate" checked>
                                    <label class="form-check-label" for="gridRadios1">
                                        Immediate(2-24 hours)
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="Stand By">
                                    <label class="form-check-label" for="gridRadios2">
                                        Stand By(24-48 hours)
                                    </label>
                                </div>
                                <div class="form-check disabled">
                                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios3" value="Long Term">
                                    <label class="form-check-label" for="gridRadios3">
                                        Long Term
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Add Note</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" style="height: 100px" name="note" id="note"></textarea>
                            </div>
                        </div>
                        <div class="row mb-3" >
                            <label class="col-sm-2 col-form-label"></label>
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary-submit" style="margin:auto">Confirm Request</button>
<!--                                <input type=button class="btn btn-primary-submit" onClick="processRequest();" value="Confirm Request">-->
                            </div>
                        </div>
                </form>
                <!-- End General Form Elements -->
            </div>
        </div>
    </div>
    </form><!-- End General Form Elements -->
    </div>
    </div>
    </div>
    </div>
</section>
{% endblock %}


{% block script %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<script>
    function myMap() {
        const myLatLng = {
            lat: 23.807145,
            lng: 90.363633
        };
        var mapProp = {
            center: myLatLng,
            zoom: 17,
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

        var marker = new google.maps.Marker({
            position: myLatLng,
            animation: google.maps.Animation.DROP
        });

        marker.setDraggable(true);
        marker.setClickable(true);
        marker.setMap(map);
        marker.addListener('position_changed', printMarkerLocation);

        function printMarkerLocation() {
            var pos = 'Lat: ' + marker.position.lat() + ' Lng:' + marker.position.lng();
            console.log(pos);
            document.getElementById("address").value = pos
        }
    }
</script>

<script>
    function processRequest() {
        var name = document.getElementById("name");
        var phone = document.getElementById("phone");
        var address = document.getElementById("address");
        var hospital = document.getElementById("hospital");
        var blood_type = document.getElementById("blood_type");
        var prescription = document.getElementById("prescription");
        var urgencyCollection = document.getElementsByName("gridRadios");
        var urgency = "";
        for(var i = 0; i < urgencyCollection.length; i++)
            if(urgencyCollection[i].type == "radio" && urgencyCollection[i].checked)
                urgency = urgencyCollection[i];

        var date = document.getElementById("required_date");

        if(name.value.length == 0) {
            alert("Name field is required!!");
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            return;
        }
        if(phone.value.length == 0) {
            alert("Phone field is required!!");
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            return;
        }
        if(address.value.length == 0) {
            alert("Address field is required!!");
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            return;
        }
        if(prescription.files.length == 0) {
            alert("Prescription field is required!!");
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            return;
        }
        var data =  "name: " + name.value + "\n" +
                    "phone: " + phone.value + "\n" +
                    "address: " + address.value + "\n" +
                    "hospital: " + hospital.value + "\n" +
                    "blood_type: " + blood_type.value + "\n" +
                    "urgency: " + urgency.value + "\n" +
                    "date: " + required_date.value + "\n"

        window.location.href = "http://127.0.0.1:8000/createRequest/process/";

<!--        $.ajax({-->
<!--            url: "{% url 'createRequest:processRequest' %}",-->
<!--            data: {-->
<!--                'name': name.value,-->
<!--                'phone': phone.value,-->
<!--                'address': address.value,-->
<!--                'hospital': hospital.value,-->
<!--                'blood_type': blood_type.value,-->
<!--                'urgency': urgency.value,-->
<!--                'date': required_date.value-->
<!--            },-->
<!--            datatype: 'json',-->
<!--            success: function(data) {-->
<!--                alert("Request Successful! Checkout homepage");-->
<!--            },-->
<!--            error: function() {-->
<!--                alert("Something went wrong. Reload the page");-->
<!--            }-->
<!--        });-->

    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzH5qc_mytBR1OydCEd87eKZ-_u-fP8sQ&callback=myMap"></script>
{% endblock %}

templates/sidebar.html
{% load static %}
<!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span> Request Blood  </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'createRequest:index' %}">
              <i class="bi bi-circle"></i><span>Regular</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Long Term</span>
            </a>
          </li>
        </ul>
      </li><!-- End Forms Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-layout-text-window-reverse"></i><span> Check Requests  </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>General Requests</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Referred From Friend</span>
            </a>
          </li>
        </ul>
      </li><!-- End Tables Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
          <i class="fa-solid fa-user-group"></i><span> Friends  </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Friend Requests</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>All Friends</span>
            </a>
          </li>
        </ul>
      </li><!-- End Charts Nav -->



      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
          <i class="fa-solid fa-droplet"></i><span> Blood Donations  </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Recents</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>All</span>
            </a>
          </li>
        </ul>
      </li><!-- End Icons Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
         <i class="fa-solid fa-hospital"></i><span> Blood Banks  </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Your Blood Banks</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>All Blood Banks</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Suggested Blood Banks</span>
            </a>
          </li>
        </ul>
      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed"  href="#">
          <i class="fa-solid fa-hand-holding-droplet"></i><span> Donate Blood</span>
        </a>
      </li><!-- End Icons Nav -->

      <hr class="solid">

      <li class="nav-item">
        <a class="nav-link collapsed" href="#">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="#">
          <i class="bi bi-question-circle"></i>
          <span>F.A.Q</span>
        </a>
      </li><!-- End F.A.Q Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="#">
          <i class="bi bi-envelope"></i>
          <span>Contact</span>
        </a>
      </li><!-- End Contact Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="#">
          <i class="bi bi-card-list"></i>
          <span>About us</span>
        </a>
      </li><!-- End Register Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="#">
          <i class="bi bi-box-arrow-in-right"></i>
          <span>Sign out</span>
        </a>
      </li><!-- End Login Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->